### get-status
GET {{server-url}}/pub-sub-demo
Accept: application/json

### start-pub-sub-kafka-rest-proxy
POST {{server-url}}/pub-sub-demo
Accept: application/json
Content-Type: application/json

{
  "mode": "CONSUMER_AND_PRODUCERS",
  "type": "KAFKA_REST_PROXY",
  "minBatchIntervalMs": 100,
  "maxBatchIntervalMs": 100,
  "minMessagePayloadSizeBytes": 180000,
  "maxMessagePayloadSizeBytes": 180000,
  "parallelProducers": 4,
  "gatherLatencies": true,
  "kafkaRestUri": "{{kafka-rest-uri}}",
  "kafkaUserName": "{{kafka-user-name}}",
  "kafkaUserPassword": "{{kafka-password}}",
  "kafkaTopic": "latency-test-topic-1",
  "valueSchemaId": "7",
  "kafkaConsumerGroup": "consumer-group-{{$uuid}}",
  "kafkaConsumerId": "consumer-{{$uuid}}",
  "minMessagesPerBatch": 4,
  "maxMessagesPerBatch": 4,
  "consumeTimeoutMs": 10,
  "consumeMaxBytesMs": 5000000,
  "commitInterval": "PT10S"
}

### stop-pub-sub
DELETE {{server-url}}/pub-sub-demo
