### get-status
GET {{server-url}}/pub-sub-demo
Accept: application/json

### start-pub-sub-kafka-rest-proxy
POST {{server-url}}/pub-sub-demo
Accept: application/json
Content-Type: application/json

{
  "type": "KAFKA_REST_PROXY",
  "minIntervalMs": 500,
  "maxIntervalMs": 1501,
  "minMessagePayloadSizeBytes": 200000,
  "maxMessagePayloadSizeBytes": 200001,
  "parallelProducers": 1,
  "gatherLatencies": true,
  "kafkaRestUri": "{{kafka-rest-uri}}",
  "kafkaUserName": "{{kafka-user-name}}",
  "kafkaUserPassword": "{{kafka-password}}",
  "kafkaTopic": "latency-test-topic-1",
  "valueSchemaId": "7",
  "kafkaConsumerGroup": "consumer-group-{{$uuid}}",
  "kafkaConsumerId": "consumer-{{$uuid}}",
  "minMessagesPerBatch": 1,
  "maxMessagesPerBatch": 2,
  "consumeTimeoutMs": 5000,
  "consumeMaxBytesMs": 10000,
  "commitInterval": "PT10S"
}

### stop-pub-sub
DELETE {{server-url}}/pub-sub-demo
